cp /data_fedor12/robin/TripleDistilled/ACI_EurMcwi/READY_FOR_DENOVO_RP.fastq /data_fedor12/robin/TripleDistilled/ACI_EurMcwi/ACI_EurMcwi.fastq
cp /data_fedor12/robin/TripleDistilled/BBDP_Wor/READY_FOR_DENOVO_RP.fastq /data_fedor12/robin/TripleDistilled/BBDP_Wor/BBDP_Wor.fastq
cp /data_fedor12/robin/TripleDistilled/BGI_F344/READY_FOR_DENOVO_RP.fastq /data_fedor12/robin/TripleDistilled/BGI_F344/BGI_F344.fastq
cp /data_fedor12/robin/TripleDistilled/BNLX_Cub_Prin/READY_FOR_DENOVO_RP.fastq /data_fedor12/robin/TripleDistilled/BNLX_Cub_Prin/BNLX_Cub_Prin.fastq
cp /data_fedor12/robin/TripleDistilled/DA/READY_FOR_DENOVO_RP.fastq /data_fedor12/robin/TripleDistilled/DA/DA.fastq
cp /data_fedor12/robin/TripleDistilled/F344_Ncrl/READY_FOR_DENOVO_RP.fastq /data_fedor12/robin/TripleDistilled/F344_Ncrl/F344_Ncrl.fastq
cp /data_fedor12/robin/TripleDistilled/F344_Prin/READY_FOR_DENOVO_RP.fastq /data_fedor12/robin/TripleDistilled/F344_Prin/F344_Prin.fastq
cp /data_fedor12/robin/TripleDistilled/F344/READY_FOR_DENOVO_RP.fastq /data_fedor12/robin/TripleDistilled/F344/F344.fastq
cp /data_fedor12/robin/TripleDistilled/FHH_EurMcwi/READY_FOR_DENOVO_RP.fastq /data_fedor12/robin/TripleDistilled/FHH_EurMcwi/FHH_EurMcwi.fastq
cp /data_fedor12/robin/TripleDistilled/FHL_EurMcwi/READY_FOR_DENOVO_RP.fastq /data_fedor12/robin/TripleDistilled/FHL_EurMcwi/FHL_EurMcwi.fastq
cp /data_fedor12/robin/TripleDistilled/GK_Ox/READY_FOR_DENOVO_RP.fastq /data_fedor12/robin/TripleDistilled/GK_Ox/GK_Ox.fastq
cp /data_fedor12/robin/TripleDistilled/LE_STM/READY_FOR_DENOVO_RP.fastq /data_fedor12/robin/TripleDistilled/LE_STM/LE_STM.fastq
cp /data_fedor12/robin/TripleDistilled/LEW_Crl/READY_FOR_DENOVO_RP.fastq /data_fedor12/robin/TripleDistilled/LEW_Crl/LEW_Crl.fastq
cp /data_fedor12/robin/TripleDistilled/LEW_NCrlBR/READY_FOR_DENOVO_RP.fastq /data_fedor12/robin/TripleDistilled/LEW_NCrlBR/LEW_NCrlBR.fastq
cp /data_fedor12/robin/TripleDistilled/LH_MavRrrc/READY_FOR_DENOVO_RP.fastq /data_fedor12/robin/TripleDistilled/LH_MavRrrc/LH_MavRrrc.fastq
cp /data_fedor12/robin/TripleDistilled/LL_MavRrrc/READY_FOR_DENOVO_RP.fastq /data_fedor12/robin/TripleDistilled/LL_MavRrrc/LL_MavRrrc.fastq
cp /data_fedor12/robin/TripleDistilled/LN_MavRrrc/READY_FOR_DENOVO_RP.fastq /data_fedor12/robin/TripleDistilled/LN_MavRrrc/LN_MavRrrc.fastq
cp /data_fedor12/robin/TripleDistilled/MHS_Gib/READY_FOR_DENOVO_RP.fastq /data_fedor12/robin/TripleDistilled/MHS_Gib/MHS_Gib.fastq
cp /data_fedor12/robin/TripleDistilled/MNS_Gib/READY_FOR_DENOVO_RP.fastq /data_fedor12/robin/TripleDistilled/MNS_Gib/MNS_Gib.fastq
cp /data_fedor12/robin/TripleDistilled/SBH_Ygl/READY_FOR_DENOVO_RP.fastq /data_fedor12/robin/TripleDistilled/SBH_Ygl/SBH_Ygl.fastq
cp /data_fedor12/robin/TripleDistilled/SBN_Ygl/READY_FOR_DENOVO_RP.fastq /data_fedor12/robin/TripleDistilled/SBN_Ygl/SBN_Ygl.fastq
cp /data_fedor12/robin/TripleDistilled/SHR_NCrl_Prin/READY_FOR_DENOVO_RP.fastq /data_fedor12/robin/TripleDistilled/SHR_NCrl_Prin/SHR_NCrl_Prin.fastq
cp /data_fedor12/robin/TripleDistilled/SHR_NHsd/READY_FOR_DENOVO_RP.fastq /data_fedor12/robin/TripleDistilled/SHR_NHsd/SHR_NHsd.fastq
cp /data_fedor12/robin/TripleDistilled/SHR_OlaIpcv_Prin/READY_FOR_DENOVO_RP.fastq /data_fedor12/robin/TripleDistilled/SHR_OlaIpcv_Prin/SHR_OlaIpcv_Prin.fastq
cp /data_fedor12/robin/TripleDistilled/SHR_olalPcv/READY_FOR_DENOVO_RP.fastq /data_fedor12/robin/TripleDistilled/SHR_olalPcv/SHR_olalPcv.fastq
cp /data_fedor12/robin/TripleDistilled/SHRSP_Gla/READY_FOR_DENOVO_RP.fastq /data_fedor12/robin/TripleDistilled/SHRSP_Gla/SHRSP_Gla.fastq
cp /data_fedor12/robin/TripleDistilled/SR_Jr/READY_FOR_DENOVO_RP.fastq /data_fedor12/robin/TripleDistilled/SR_Jr/SR_Jr.fastq
cp /data_fedor12/robin/TripleDistilled/SS_JrHsdMcwi/READY_FOR_DENOVO_RP.fastq /data_fedor12/robin/TripleDistilled/SS_JrHsdMcwi/SS_JrHsdMcwi.fastq
cp /data_fedor12/robin/TripleDistilled/SS_Jr/READY_FOR_DENOVO_RP.fastq /data_fedor12/robin/TripleDistilled/SS_Jr/SS_Jr.fastq
cp /data_fedor12/robin/TripleDistilled/tadao_F344/READY_FOR_DENOVO_RP.fastq /data_fedor12/robin/TripleDistilled/tadao_F344/tadao_F344.fastq
cp /data_fedor12/robin/TripleDistilled/WAG_Rij/READY_FOR_DENOVO_RP.fastq /data_fedor12/robin/TripleDistilled/WAG_Rij/WAG_Rij.fastq
cp /data_fedor12/robin/TripleDistilled/WKY_Gla/READY_FOR_DENOVO_RP.fastq /data_fedor12/robin/TripleDistilled/WKY_Gla/WKY_Gla.fastq
cp /data_fedor12/robin/TripleDistilled/WKY_NCrl/READY_FOR_DENOVO_RP.fastq /data_fedor12/robin/TripleDistilled/WKY_NCrl/WKY_NCrl.fastq
cp /data_fedor12/robin/TripleDistilled/WKY_NHsd/READY_FOR_DENOVO_RP.fastq /data_fedor12/robin/TripleDistilled/WKY_NHsd/WKY_NHsd.fastq
